# Generated by Django 3.2.4 on 2021-06-12 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='名称')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.permission', verbose_name='上级权限')),
            ],
            options={
                'verbose_name': '权限',
                'verbose_name_plural': '权限',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='名称')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.role', verbose_name='上级角色')),
                ('permissions', models.ManyToManyField(blank=True, to='user.Permission', verbose_name='权限集')),
            ],
            options={
                'verbose_name': '角色',
                'verbose_name_plural': '角色',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('openid', models.CharField(max_length=255, unique=True, verbose_name='openid')),
                ('nickname', models.CharField(max_length=50, unique=True, verbose_name='昵称')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='生日')),
                ('last', models.DateTimeField(blank=True, null=True, verbose_name='上次登陆')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='邮箱')),
                ('phone', models.CharField(blank=True, max_length=13, null=True, verbose_name='手机')),
                ('gender', models.PositiveSmallIntegerField(choices=[(0, '女'), (1, '男'), (2, '其他')], verbose_name='性别')),
                ('brief', models.TextField(blank=True, null=True, verbose_name='简介')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='images', verbose_name='头像')),
                ('resume', models.FileField(blank=True, null=True, upload_to='files', verbose_name='简历')),
                ('height', models.FloatField(default=1.8, verbose_name='身高')),
                ('wallet', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='钱包')),
                ('married', models.BooleanField(default=False, verbose_name='是否结婚')),
                ('roles', models.ManyToManyField(blank=True, to='user.Role', verbose_name='角色集')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('permissions', models.ManyToManyField(blank=True, to='user.Permission', verbose_name='权限集')),
                ('users', models.ManyToManyField(blank=True, to='user.User', verbose_name='用户群')),
            ],
            options={
                'verbose_name': '组',
                'verbose_name_plural': '组',
            },
        ),
    ]
