# Generated by Django 3.2.4 on 2021-07-08 05:58

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AntdCasbinRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ptype', models.CharField(choices=[('p', '策略'), ('g', '角色')], max_length=10)),
                ('v0', models.CharField(blank=True, max_length=255, null=True)),
                ('v1', models.CharField(blank=True, max_length=255, null=True)),
                ('v2', models.CharField(blank=True, max_length=255, null=True)),
                ('v3', models.CharField(blank=True, max_length=255, null=True)),
                ('v4', models.CharField(blank=True, max_length=255, null=True)),
                ('v5', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'casbin规则',
                'verbose_name_plural': 'casbin规则',
                'db_table': 'casbin_rule',
            },
        ),
        migrations.CreateModel(
            name='AntdPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否软删除')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='名称')),
                ('method', models.CharField(choices=[('get', 'get'), ('post', 'post'), ('put', 'put'), ('delete', 'delete')], max_length=10, verbose_name='请求方法')),
                ('route', models.CharField(max_length=255, verbose_name='路由，支持正则')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='antd_pro.antdpermission', verbose_name='上级权限')),
            ],
            options={
                'verbose_name': '权限',
                'verbose_name_plural': '权限',
            },
        ),
        migrations.CreateModel(
            name='AntdRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否软删除')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='名称')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='antd_pro.antdrole', verbose_name='上级角色')),
                ('permissions', models.ManyToManyField(blank=True, to='antd_pro.AntdPermission', verbose_name='权限集')),
            ],
            options={
                'verbose_name': '角色',
                'verbose_name_plural': '角色',
            },
        ),
        migrations.CreateModel(
            name='AntdUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否软删除')),
                ('is_super', models.BooleanField(default=False, verbose_name='是否超管')),
                ('phone_num', models.CharField(max_length=11, unique=True, validators=[django.core.validators.RegexValidator('1[345678]\\d{9}', message='请输入正确的手机号')], verbose_name='手机号')),
                ('password', models.CharField(max_length=50, verbose_name='密码')),
                ('roles', models.ManyToManyField(blank=True, to='antd_pro.AntdRole', verbose_name='角色集')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
            },
        ),
        migrations.CreateModel(
            name='AntdUserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否软删除')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='images', verbose_name='头像')),
                ('birthday', models.DateTimeField(blank=True, null=True, verbose_name='生日')),
                ('gender', models.PositiveSmallIntegerField(blank=True, choices=[(0, '女'), (1, '男'), (2, '其他')], null=True, verbose_name='性别')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='邮箱')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='antd_pro.antduser', verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户信息',
                'verbose_name_plural': '用户信息',
            },
        ),
    ]
