# Generated by Django 3.2.4 on 2021-07-08 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('antd_pro', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='antduser',
            name='password',
            field=models.CharField(max_length=250, verbose_name='密码'),
        ),
    ]
