# Generated by Django 3.2.4 on 2021-07-08 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('antd_pro', '0002_alter_antduser_password'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AntdCasbinRule',
        ),
    ]
