# Generated by Django 3.2.4 on 2021-06-12 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CasbinRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ptype', models.CharField(choices=[('p', '策略'), ('g', '角色')], max_length=10)),
                ('v0', models.CharField(max_length=255)),
                ('v1', models.CharField(max_length=255)),
                ('v2', models.CharField(max_length=255)),
                ('v3', models.CharField(blank=True, max_length=255, null=True)),
                ('v4', models.CharField(blank=True, max_length=255, null=True)),
                ('v5', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'casbin规则',
                'verbose_name_plural': 'casbin规则',
                'db_table': 'casbin_rule',
            },
        ),
    ]
