"""
Django settings for django_love_ant project.

Generated by 'django-admin startproject' using Django 3.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

from pathlib import Path
import sys
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

sys.path.append(os.path.join(BASE_DIR, 'apps'))

sys.path.append(os.path.join(BASE_DIR, 'plugins'))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-3m&k@ycti&ci620948+g7v71h6j)tc#-yfoz-oy1zm4yrvk+p&'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_filters',
    'user',
    'order',
    'antd_pro'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates']
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'wsgi.application'

# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = '/static/'

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

MEDIA_URL = '/media/'

MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

ANTD = {
    'ANTD_DIST': os.path.join(BASE_DIR, 'mycode'),
    'ANTD_RSA_PUBLIC_KEY': b"""-----BEGIN PUBLIC KEY-----
MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCm0+YWuN3dRa5tCmoEW0A0Ly5w
+Ci9ArKpkMywUoPWdWKUcEVnQXDFa3FYiYmo8VidhPkutqq/sGxMxTRHhFXpsMyr
fxZpNGsPpy1HaCg+7+4Lt4qudtU1+JVlUVby3Y6hOS7ckY870bPQSuI2WbojwfHI
UJUMauiMWeIrOOXRNwIDAQAB
-----END PUBLIC KEY-----
""",
    'ANTD_RSA_PRIVATE_KEY': b"""-----BEGIN RSA PRIVATE KEY-----
MIICXQIBAAKBgQCm0+YWuN3dRa5tCmoEW0A0Ly5w+Ci9ArKpkMywUoPWdWKUcEVn
QXDFa3FYiYmo8VidhPkutqq/sGxMxTRHhFXpsMyrfxZpNGsPpy1HaCg+7+4Lt4qu
dtU1+JVlUVby3Y6hOS7ckY870bPQSuI2WbojwfHIUJUMauiMWeIrOOXRNwIDAQAB
AoGBAJ4jIOkLBixYgBYWmBZXFU4iJ0iow50fMJJxksXVAenJTc/deLx/GNHang/K
GDaPyGtQgBAa0VJxfsdq67qbI/+gTgvC9BjVNQlfm99hbiKkUXC/vdj38adOY5Ag
KRO6XBoDqQgkTIHPeTn17vDFUUEoZ5PYzoO6yPOuZU9gkOm5AkEA1Bpx8jfiw6ox
9dKhlUa2p0i5CuckVnyw+IaQPRPN3mG+lQtFUPmmWVH42W2i+/lKz87a9byrAdBv
F3w1mUSsiwJBAMlar2cU4VECzjhuPyBquk4TpXDnkFEVr7quArw6QqpHNCT7Rv0u
T4TOcemwpYenccxO3Np2atNQkW/wGpitJ4UCQDzpf1HFdO0mQoTLQbZCAZCXFPUp
nkjsNFKbKm8v8c5smbPp8bUojPpXzTR8BPOCC1cUm9M4pI+30T+YXzgt/bMCQQDB
+830P1d7FnraPswuTORECAVhKpYMqBnufWpBMNe8+HAyGKshi5YsWj/AZeBzOkwW
CvwWs/LitkIHV4goAtmJAkBbRCthfljuHxTYi/E1vN2lvXcCYKwI6DX1HddWtWnn
X24znrq1+c/UQL49Q1n8nMzaP85AWYeF4kOSfTV3bX3d
-----END RSA PRIVATE KEY-----
"""
}
