# Generated by Django 3.1.7 on 2021-03-02 08:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('casbin_adapter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='casbinrule',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='create time'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='casbinrule',
            name='is_delete',
            field=models.BooleanField(default=False, verbose_name='is deleted'),
        ),
        migrations.AddField(
            model_name='casbinrule',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='order, the bigger, the farther forward'),
        ),
        migrations.AddField(
            model_name='casbinrule',
            name='update_time',
            field=models.DateTimeField(auto_now=True, verbose_name='update time'),
        ),
    ]
