# Generated by Django 3.1.7 on 2021-03-02 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casbin_adapter', '0002_auto_20210302_1604'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='casbinrule',
            options={'verbose_name': 'casbin规则', 'verbose_name_plural': 'casbin规则'},
        ),
        migrations.AlterField(
            model_name='casbinrule',
            name='ptype',
            field=models.CharField(choices=[('p', '策略'), ('g', '角色')], max_length=10),
        ),
        migrations.AlterField(
            model_name='casbinrule',
            name='v3',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='casbinrule',
            name='v4',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='casbinrule',
            name='v5',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
