# Generated by Django 2.2.6 on 2021-04-20 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casbin_adapter', '0003_auto_20210302_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casbinrule',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='casbinrule',
            name='is_delete',
            field=models.BooleanField(default=False, verbose_name='是否软删'),
        ),
        migrations.AlterField(
            model_name='casbinrule',
            name='order',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='优先级'),
        ),
        migrations.AlterField(
            model_name='casbinrule',
            name='update_time',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
    ]
