# Generated by Django 3.2.4 on 2021-07-08 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casbin_adapter', '0004_auto_20210420_1516'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='casbinrule',
            name='order',
        ),
        migrations.AlterField(
            model_name='casbinrule',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='casbinrule',
            name='is_delete',
            field=models.BooleanField(default=False, verbose_name='是否软删除'),
        ),
    ]
